name: Publish Docs

on:
  release:
  workflow_dispatch:

env:
  VOLTA_FEATURE_PNPM: 1

jobs:
  publish:
    name: 'Build and publish docs'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4

      - run: pnpm install

      - name: Update to latest supported TS version to match TypeDoc requirements
        run: pnpm add --save-dev typescript@latest

      - name: Build docs
        run: pnpm doc

      - name: Publish docs
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages
          folder: docs-dist
